namespace Meitou.Rendering.Characters;

/// <summary>
/// The character renderer's environment switches, read once when the type is first used (docs/character-renderer.md "Env").
/// (Not <c>CharacterOptions</c>: that name is <c>Meitou.Data.Characters.CharacterOptions</c>.)
/// </summary>
internal static class CharacterSwitches
{
    static string? Read(string name) => Environment.GetEnvironmentVariable(name);

    /// <summary><c>MEITOU_CHARACTER_LOG=1</c>: a line per part of every appearance built (levels, triangles, material).</summary>
    public static readonly bool Log = Read("MEITOU_CHARACTER_LOG") == "1";

    /// <summary>Meitou mode, the default: mesh levels generated by edge collapse for every mesh. <c>MEITOU_CHARACTER_LOD=faithful</c> keeps the files' own levels.</summary>
    public static readonly bool GenerateLods = Read("MEITOU_CHARACTER_LOD") != "faithful";

    /// <summary><c>MEITOU_CHARACTER_MORPH=0</c> turns the face poses (GPU morph of the body mesh) off.</summary>
    public static readonly bool Morphs = Read("MEITOU_CHARACTER_MORPH") != "0";

    /// <summary><c>MEITOU_CHARACTER_MOTION=0</c> leaves the characters' own motion out of the temporal upscalers' motion vectors.</summary>
    public static readonly bool MotionVectors = Read("MEITOU_CHARACTER_MOTION") != "0";

    /// <summary><c>MEITOU_CROWD_ANIMATE=1</c>: the <c>--crowd</c> harness animates in real time even for stills (otherwise stills hold <c>--crowd-time</c>).</summary>
    public static readonly bool CrowdAnimate = Read("MEITOU_CROWD_ANIMATE") == "1";
}
